version: "3.8"
services:
   web:
      build: .
      container_name: app
      ports:
      - "1234:5050"
      links:
      - db
   db:
      image: mongo
      container_name: mongodb
      ports:
      - 27017:27017