apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-compose-flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-compose-flask-app
  template:
    metadata:
      labels:
        app: docker-compose-flask-app
    spec:
      containers:
        - name: docker-compose-flask-app
          image: x64nik/docker-compose-flask-app:docker-compose-flask-app
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: docker-compose-flask-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: docker-compose-flask-app
