apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /opt/kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /opt/kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-compose-flask-app-default: "true"
        io.kompose.service: web
    spec:
      containers:
        - image: web
          name: app
          ports:
            - containerPort: 5050
          resources: {}
      restartPolicy: Always
status: {}
